# fly.toml app configuration file generated for hampapi on 2023-08-21T16:46:27-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hampapi"
primary_region = "bos"

[build]

[http_service]
  internal_port = 1323
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[checks]
  [checks.http_is_alive]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/"
    port = 1323
    timeout = "10s"
    type = "http"